"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import {
  Zap,
  ArrowRight,
  Upload,
  Search,
  ShieldCheck,
  GitBranch,
  BarChart3,
  FileText,
  Link2,
  FileType,
  CheckCircle2,
  Code2,
  Star,
  Quote,
  Menu,
  X,
} from "lucide-react";

const fadeUp = {
  hidden: { opacity: 0, y: 18 },
  visible: (i: number = 0) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, delay: i * 0.08, ease: [0.22, 1, 0.36, 1] },
  }),
};

const pipeline = [
  {
    icon: Upload,
    step: "01",
    title: "Ingest",
    body: "Drop in a PDF, DOCX, URL, or raw text. Documents are chunked with a sliding window and vectorised in seconds.",
  },
  {
    icon: Search,
    step: "02",
    title: "Retrieve",
    body: "TF-IDF vectors search a FAISS index with a minimum similarity threshold, surfacing only genuinely relevant chunks.",
  },
  {
    icon: Zap,
    step: "03",
    title: "Generate",
    body: "LLaMA 3.3 70B answers strictly from retrieved context, with inline source attribution on every claim.",
  },
  {
    icon: ShieldCheck,
    step: "04",
    title: "Verify",
    body: "Every claim is cross-checked against the source chunks and flagged individually if it isn't grounded.",
  },
];

const features = [
  {
    icon: GitBranch,
    title: "Source Trace",
    body: "Expand any answer down to the exact chunk it came from, with per-chunk similarity scores.",
  },
  {
    icon: ShieldCheck,
    title: "Claim Verification",
    body: "Claim-level hallucination detection flags unsupported statements before you trust them.",
  },
  {
    icon: BarChart3,
    title: "Evaluation Dashboard",
    body: "Track confidence calibration, retrieval quality, and latency across every query you run.",
  },
  {
    icon: FileText,
    title: "Structured Summaries",
    body: "Auto-generated TLDR, key concepts, methodology, results, and limitations for every document.",
  },
];

const formats = [
  { icon: FileType, label: "PDF" },
  { icon: FileText, label: "DOCX" },
  { icon: FileType, label: "TXT" },
  { icon: Link2, label: "URL" },
];

const stats = [
  { value: "0.45", label: "Min. similarity threshold" },
  { value: "<3s", label: "Typical generation latency" },
  { value: "70B", label: "Parameter LLaMA model" },
  { value: "384", label: "TF-IDF feature dimensions" },
];

const testimonials = [
  {
    quote:
      "The source trace view changed how our lab reviews AI-generated summaries. We can see exactly which passage backs every claim.",
    name: "Aditi Rao",
    role: "PhD Researcher, Computational Biology",
  },
  {
    quote:
      "Claim-level verification caught a hallucinated statistic in the first week. That alone justified rolling it out to the whole team.",
    name: "Marcus Feld",
    role: "Research Engineer",
  },
  {
    quote:
      "Ingest a paper, ask a question, get an answer with citations you can actually click through. It's the workflow I always wanted.",
    name: "Priya Nair",
    role: "Graduate Student, NLP",
  },
];

const faqs = [
  {
    q: "What document formats can I upload?",
    a: "PDF, DOCX, and plain text files, along with URLs that Prism will scrape and clean before ingestion, and raw pasted text for abstracts or excerpts.",
  },
  {
    q: "How does Prism prevent hallucinated answers?",
    a: "Every generated claim is cross-checked against the retrieved source chunks. Claims that aren't grounded in the retrieved context are flagged with a warning badge rather than presented as fact.",
  },
  {
    q: "Can I see why a chunk was retrieved?",
    a: "Yes. The Source Trace view shows every retrieved chunk alongside its similarity score, so you can audit exactly why the model saw what it saw.",
  },
  {
    q: "Is my data persisted between sessions?",
    a: "Documents are indexed in-memory for the duration of your session. You can re-ingest at any time, and your query history is available in the Evaluation dashboard.",
  },
  {
    q: "Which model powers generation?",
    a: "Answers are generated by LLaMA 3.3 70B via Groq, run at a low temperature for factual consistency, with a system prompt that strictly enforces grounding rules.",
  },
];

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  return (
    <div className="min-h-screen w-full bg-[var(--bg-base)]">
      <header className="sticky top-0 z-50 border-b border-[var(--border)] bg-[var(--bg-glass)] backdrop-blur-md">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2.5 no-underline">
            <div className="flex h-8 w-8 items-center justify-center rounded-md bg-[var(--text-primary)]">
              <Zap size={15} color="var(--bg-surface)" strokeWidth={2.5} />
            </div>
            <span className="font-display text-xl leading-none tracking-tight text-[var(--text-primary)]">
              Prism
            </span>
          </Link>

          <nav className="hidden items-center gap-8 md:flex">
            <a href="#pipeline" className="font-sans text-[13.5px] font-medium text-[var(--text-secondary)] no-underline transition-colors hover:text-[var(--text-primary)]">
              Pipeline
            </a>
            <a href="#features" className="font-sans text-[13.5px] font-medium text-[var(--text-secondary)] no-underline transition-colors hover:text-[var(--text-primary)]">
              Features
            </a>
            <a href="#testimonials" className="font-sans text-[13.5px] font-medium text-[var(--text-secondary)] no-underline transition-colors hover:text-[var(--text-primary)]">
              Testimonials
            </a>
            <a href="#faq" className="font-sans text-[13.5px] font-medium text-[var(--text-secondary)] no-underline transition-colors hover:text-[var(--text-primary)]">
              FAQ
            </a>
          </nav>

          <div className="hidden items-center gap-3 md:flex">
            <Link href="/login" className="btn-secondary">
              Log in
            </Link>
            <Link href="/register" className="btn-primary">
              Get started
              <ArrowRight size={14} strokeWidth={2.5} />
            </Link>
          </div>

          <button
            aria-label="Toggle menu"
            onClick={() => setMenuOpen((v) => !v)}
            className="flex h-9 w-9 items-center justify-center rounded-md border border-[var(--border-strong)] text-[var(--text-primary)] md:hidden"
          >
            {menuOpen ? <X size={17} /> : <Menu size={17} />}
          </button>
        </div>

        {menuOpen && (
          <div className="border-t border-[var(--border)] px-6 py-4 md:hidden">
            <div className="flex flex-col gap-4">
              <a href="#pipeline" onClick={() => setMenuOpen(false)} className="font-sans text-sm font-medium text-[var(--text-secondary)] no-underline">
                Pipeline
              </a>
              <a href="#features" onClick={() => setMenuOpen(false)} className="font-sans text-sm font-medium text-[var(--text-secondary)] no-underline">
                Features
              </a>
              <a href="#testimonials" onClick={() => setMenuOpen(false)} className="font-sans text-sm font-medium text-[var(--text-secondary)] no-underline">
                Testimonials
              </a>
              <a href="#faq" onClick={() => setMenuOpen(false)} className="font-sans text-sm font-medium text-[var(--text-secondary)] no-underline">
                FAQ
              </a>
              <div className="mt-2 flex gap-3">
                <Link href="/login" className="btn-secondary flex-1 justify-center">
                  Log in
                </Link>
                <Link href="/register" className="btn-primary flex-1 justify-center">
                  Get started
                </Link>
              </div>
            </div>
          </div>
        )}
      </header>

      <section className="relative overflow-hidden px-6 pb-24 pt-20 md:pt-28">
        <div
          className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[560px]"
          style={{
            background:
              "radial-gradient(60% 60% at 50% 0%, var(--accent-light) 0%, transparent 70%)",
          }}
        />
        <div className="mx-auto max-w-4xl text-center">
          <motion.div
            initial="hidden"
            animate="visible"
            custom={0}
            variants={fadeUp}
            className="tag tag-indigo mx-auto mb-6 w-fit"
          >
            <Zap size={11} strokeWidth={2.5} />
            Retrieval-augmented, claim-verified
          </motion.div>

          <motion.h1
            initial="hidden"
            animate="visible"
            custom={1}
            variants={fadeUp}
            className="mx-auto max-w-3xl text-4xl text-[var(--text-primary)] sm:text-5xl md:text-6xl"
          >
            Research answers you can actually verify
          </motion.h1>

          <motion.p
            initial="hidden"
            animate="visible"
            custom={2}
            variants={fadeUp}
            className="mx-auto mt-6 max-w-2xl font-sans text-base leading-relaxed text-[var(--text-secondary)] md:text-lg"
          >
            Prism transforms academic documents into a queryable, grounded research
            workspace. Every answer is traced to its source chunk and checked,
            claim by claim, before you trust it.
          </motion.p>

          <motion.div
            initial="hidden"
            animate="visible"
            custom={3}
            variants={fadeUp}
            className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row"
          >
            <Link href="/register" className="btn-primary px-7 py-3.5 text-[14.5px]">
              Start for free
              <ArrowRight size={15} strokeWidth={2.5} />
            </Link>
            <a
              href="https://github.com/yamini-nlp/prism"
              target="_blank"
              rel="noreferrer"
              className="btn-secondary px-7 py-3.5 text-[14.5px]"
            >
              <Code2 size={15} />
              View on GitHub
            </a>
          </motion.div>

          <motion.div
            initial="hidden"
            animate="visible"
            custom={4}
            variants={fadeUp}
            className="mx-auto mt-8 flex flex-wrap items-center justify-center gap-x-6 gap-y-2"
          >
            {formats.map((f) => (
              <div key={f.label} className="flex items-center gap-1.5 font-sans text-xs font-medium text-[var(--text-muted)]">
                <f.icon size={13} strokeWidth={2} />
                {f.label}
              </div>
            ))}
          </motion.div>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.35, ease: [0.22, 1, 0.36, 1] }}
          className="mx-auto mt-16 max-w-5xl"
        >
          <div className="card overflow-hidden shadow-premium">
            <div className="flex items-center gap-1.5 border-b border-[var(--border)] px-5 py-3">
              <span className="h-2.5 w-2.5 rounded-full bg-[var(--accent-red)]" />
              <span className="h-2.5 w-2.5 rounded-full bg-[var(--accent-orange)]" />
              <span className="h-2.5 w-2.5 rounded-full bg-[var(--accent-green)]" />
              <span className="ml-3 font-mono text-[11px] text-[var(--text-muted)]">
                prism / workspace
              </span>
            </div>
            <div className="grid gap-0 p-6 md:grid-cols-[1fr_1.3fr] md:gap-6">
              <div className="flex flex-col gap-3">
                <div className="rounded-md border border-[var(--border)] bg-[var(--bg-base)] p-4">
                  <div className="mb-2 font-sans text-[11px] font-semibold uppercase tracking-wide text-[var(--text-muted)]">
                    Query
                  </div>
                  <p className="font-sans text-sm text-[var(--text-primary)]">
                    What retrieval method does this paper use, and how does it
                    compare to dense embeddings?
                  </p>
                </div>
                <div className="flex-1 rounded-md border border-[var(--border)] bg-[var(--bg-base)] p-4">
                  <div className="mb-2 font-sans text-[11px] font-semibold uppercase tracking-wide text-[var(--text-muted)]">
                    Confidence
                  </div>
                  <div className="mb-1.5 h-1.5 w-full overflow-hidden rounded-full bg-[var(--border)]">
                    <div className="h-full w-[87%] rounded-full bg-[var(--accent)]" />
                  </div>
                  <span className="font-mono text-[11px] text-[var(--text-muted)]">87% grounded</span>
                </div>
              </div>
              <div className="mt-4 rounded-md border border-[var(--border)] bg-[var(--bg-base)] p-4 md:mt-0">
                <div className="mb-2 flex items-center justify-between">
                  <span className="font-sans text-[11px] font-semibold uppercase tracking-wide text-[var(--text-muted)]">
                    Answer
                  </span>
                  <span className="tag" style={{ background: "var(--accent-green-light)", color: "var(--accent-green)" }}>
                    <CheckCircle2 size={10} strokeWidth={2.5} />
                    Verified
                  </span>
                </div>
                <p className="font-sans text-[13.5px] leading-relaxed text-[var(--text-secondary)]">
                  The paper uses TF-IDF vectorisation with a FAISS flat inner-product
                  index <span className="rounded-sm bg-[var(--accent-light)] px-1 py-0.5 font-medium text-[var(--color-brand-600)]">[source 1]</span>,
                  filtering retrievals below a 0.45 similarity threshold. Unlike dense
                  embedding models, this captures lexical overlap rather than semantic
                  similarity <span className="rounded-sm bg-[var(--accent-light)] px-1 py-0.5 font-medium text-[var(--color-brand-600)]">[source 3]</span>,
                  which the authors note as a retrieval ceiling for paraphrased queries.
                </p>
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      <section className="border-y border-[var(--border)] bg-[var(--bg-surface)] px-6 py-14">
        <div className="mx-auto grid max-w-5xl grid-cols-2 gap-8 md:grid-cols-4">
          {stats.map((s, i) => (
            <motion.div
              key={s.label}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              custom={i}
              variants={fadeUp}
              className="text-center"
            >
              <div className="font-display text-3xl text-[var(--text-primary)] md:text-4xl">
                {s.value}
              </div>
              <div className="mt-1.5 font-sans text-xs text-[var(--text-muted)]">
                {s.label}
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      <section id="pipeline" className="px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="mx-auto max-w-2xl text-center">
            <span className="tag tag-indigo mx-auto w-fit">Pipeline</span>
            <h2 className="mt-5 text-3xl text-[var(--text-primary)] md:text-4xl">
              From raw document to verified answer
            </h2>
            <p className="mt-4 font-sans text-[15px] leading-relaxed text-[var(--text-secondary)]">
              A full retrieval-augmented pipeline, exposed end to end rather than
              hidden behind a black box.
            </p>
          </div>

          <div className="mt-16 grid gap-5 md:grid-cols-4">
            {pipeline.map((p, i) => (
              <motion.div
                key={p.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                custom={i}
                variants={fadeUp}
                className="card relative flex flex-col gap-4 p-6"
              >
                <span className="font-mono text-[11px] font-medium text-[var(--text-muted)]">
                  {p.step}
                </span>
                <div className="flex h-10 w-10 items-center justify-center rounded-md bg-[var(--accent-light)]">
                  <p.icon size={18} color="var(--accent)" strokeWidth={2} />
                </div>
                <h3 className="font-display text-lg text-[var(--text-primary)]">
                  {p.title}
                </h3>
                <p className="font-sans text-[13.5px] leading-relaxed text-[var(--text-secondary)]">
                  {p.body}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section id="features" className="border-y border-[var(--border)] bg-[var(--bg-surface)] px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="mx-auto max-w-2xl text-center">
            <span className="tag tag-indigo mx-auto w-fit">Features</span>
            <h2 className="mt-5 text-3xl text-[var(--text-primary)] md:text-4xl">
              Built for auditable research
            </h2>
            <p className="mt-4 font-sans text-[15px] leading-relaxed text-[var(--text-secondary)]">
              Every layer of the retrieval and generation process is transparent
              and inspectable, not just the final answer.
            </p>
          </div>

          <div className="mt-16 grid gap-5 sm:grid-cols-2">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                custom={i}
                variants={fadeUp}
                className="card flex gap-4 p-6"
              >
                <div className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-md bg-[var(--accent-light)]">
                  <f.icon size={19} color="var(--accent)" strokeWidth={2} />
                </div>
                <div>
                  <h3 className="font-display text-lg text-[var(--text-primary)]">
                    {f.title}
                  </h3>
                  <p className="mt-1.5 font-sans text-[13.5px] leading-relaxed text-[var(--text-secondary)]">
                    {f.body}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section id="testimonials" className="px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="mx-auto max-w-2xl text-center">
            <span className="tag tag-indigo mx-auto w-fit">Testimonials</span>
            <h2 className="mt-5 text-3xl text-[var(--text-primary)] md:text-4xl">
              Trusted by researchers who check their sources
            </h2>
          </div>

          <div className="mt-16 grid gap-5 md:grid-cols-3">
            {testimonials.map((t, i) => (
              <motion.div
                key={t.name}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                custom={i}
                variants={fadeUp}
                className="card flex flex-col gap-4 p-6"
              >
                <Quote size={20} color="var(--accent)" strokeWidth={2} />
                <p className="font-sans text-[13.5px] leading-relaxed text-[var(--text-secondary)]">
                  {t.quote}
                </p>
                <div className="mt-auto flex items-center gap-0.5 pt-2">
                  {Array.from({ length: 5 }).map((_, idx) => (
                    <Star key={idx} size={12} fill="var(--accent-orange)" color="var(--accent-orange)" />
                  ))}
                </div>
                <div className="border-t border-[var(--border)] pt-4">
                  <div className="font-sans text-sm font-semibold text-[var(--text-primary)]">
                    {t.name}
                  </div>
                  <div className="font-sans text-xs text-[var(--text-muted)]">
                    {t.role}
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section id="faq" className="border-y border-[var(--border)] bg-[var(--bg-surface)] px-6 py-24">
        <div className="mx-auto max-w-3xl">
          <div className="mx-auto max-w-2xl text-center">
            <span className="tag tag-indigo mx-auto w-fit">FAQ</span>
            <h2 className="mt-5 text-3xl text-[var(--text-primary)] md:text-4xl">
              Frequently asked questions
            </h2>
          </div>

          <div className="mt-12 flex flex-col gap-3">
            {faqs.map((f, i) => (
              <div key={f.q} className="card overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left"
                >
                  <span className="font-sans text-sm font-semibold text-[var(--text-primary)]">
                    {f.q}
                  </span>
                  <span
                    className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full border border-[var(--border-strong)] font-sans text-sm text-[var(--text-secondary)] transition-transform duration-200"
                    style={{ transform: openFaq === i ? "rotate(45deg)" : "rotate(0deg)" }}
                  >
                    +
                  </span>
                </button>
                {openFaq === i && (
                  <div className="px-6 pb-5">
                    <p className="font-sans text-[13.5px] leading-relaxed text-[var(--text-secondary)]">
                      {f.a}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="px-6 py-24">
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          variants={fadeUp}
          className="relative mx-auto max-w-4xl overflow-hidden rounded-2xl px-8 py-16 text-center"
          style={{ background: "var(--text-primary)" }}
        >
          <div
            className="pointer-events-none absolute inset-0"
            style={{
              background:
                "radial-gradient(50% 80% at 50% 0%, rgba(91,94,244,0.35) 0%, transparent 70%)",
            }}
          />
          <div className="relative">
            <h2 className="text-3xl text-[var(--bg-surface)] md:text-4xl">
              Start verifying your research today
            </h2>
            <p className="mx-auto mt-4 max-w-xl font-sans text-[15px] leading-relaxed text-[var(--color-neutral-300)]">
              Ingest your first document and get a grounded, source-traced answer
              in under a minute.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <Link
                href="/register"
                className="btn-primary bg-[var(--bg-surface)] px-7 py-3.5 text-[14.5px] text-[var(--text-primary)] hover:opacity-90"
              >
                Get started free
                <ArrowRight size={15} strokeWidth={2.5} />
              </Link>
              <a
                href="https://github.com/yamini-nlp/prism"
                target="_blank"
                rel="noreferrer"
                className="btn-secondary border-[rgba(255,255,255,0.2)] px-7 py-3.5 text-[14.5px] text-[var(--bg-surface)] hover:border-[var(--bg-surface)]"
              >
                <Code2 size={15} />
                Explore the code
              </a>
            </div>
          </div>
        </motion.div>
      </section>

      <footer className="border-t border-[var(--border)] px-6 py-12">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 md:flex-row">
          <Link href="/" className="flex items-center gap-2.5 no-underline">
            <div className="flex h-7 w-7 items-center justify-center rounded-md bg-[var(--text-primary)]">
              <Zap size={13} color="var(--bg-surface)" strokeWidth={2.5} />
            </div>
            <span className="font-display text-lg leading-none tracking-tight text-[var(--text-primary)]">
              Prism
            </span>
          </Link>

          <p className="font-sans text-xs text-[var(--text-muted)]">
            Built by Yamini G — retrieval-augmented, claim-verified research.
          </p>

          <div className="flex items-center gap-5">
            <a
              href="https://github.com/yamini-nlp/prism"
              target="_blank"
              rel="noreferrer"
              className="font-sans text-xs font-medium text-[var(--text-secondary)] no-underline transition-colors hover:text-[var(--text-primary)]"
            >
              GitHub
            </a>
            <Link href="/login" className="font-sans text-xs font-medium text-[var(--text-secondary)] no-underline transition-colors hover:text-[var(--text-primary)]">
              Log in
            </Link>
            <Link href="/register" className="font-sans text-xs font-medium text-[var(--text-secondary)] no-underline transition-colors hover:text-[var(--text-primary)]">
              Register
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}