[mypy]
python_version = 3.11
ignore_missing_imports = True
warn_unused_ignores = False
disallow_untyped_defs = False
check_untyped_defs = False
no_implicit_optional = False
explicit_package_bases = True
mypy_path = .
exclude = (^alembic/|^tests/)